config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get 'resort', to: 'static_pages#resort'
  get 'price', to: 'static_pages#price'
  get 'contact', to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

  def resort
  end

  def price
  end

  def contact
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jamaica</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div id="flex-content-container">
    <nav class="navbar navbar-toggleable-lg navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
           <li class="navbar-brand, nav-link">

            <%= link_to 'Home', root_path %>
          </li>

          <li class="nav-item, nav-link">
            <%= link_to 'Resort', resort_path %>
          </li>
          <li class="nav-item, nav-link">
            <%= link_to 'Price', price_path %>
          </li>
          <li class="nav-item, nav-link">
            <%= link_to 'Contact', contact_path %>
          </li>
          <br />
        </ul>
          <div class=" nav-item audio-player">
            <%= audio_tag "music.mp3", loop: true, volume: 0.4, controls: true%>
          </div>
      </div>
    </nav>

    <%= yield %>
  </div>
  <br />
  <br />
  <br />
   <br />
   <div class="footer">
      <div class="container">
        <div class="row">

          <div class="col-12 col-sm-6 footer-blurb">
            Proudly created in Dallas, TX by <a href="http://chastitylawson.getforge.io">Chastity Lawson</a><br />
          </div>

        </div>
      </div>
    </div>

</html>

app/views/static_pages/contact.html.erb
<br />
<br />
<div class="text-center glow">
  <h1>Contact, Payments, Information </h1>
  <br />
    <div class="col-10 offset-1">
      <%= image_tag("contact.jpg", class: 'img-fluid, photo') %>
    </div>
</div>
    <br />
<br />
<br />



<div class="booyah-box col-10 offset-1">
  <div class="text-center">
    <br />
    <body>
      <p> Keisha Davis @ 281-746-4915 
      <br /> KDavis@TheSkyShops.com
      </p>
    </body>
  </div>

</div>

app/views/static_pages/index.html.erb
<body>

  <div class='hero'>
    <br />
    <br />

    <br />
    <br />
    <br />
    <br />

      <div class="frosty col-10 offset-1 text-center">
        <div class="glow">
          <h1>Cynthia's 40th Celebration</h1>
        </div>
        <br />
        <h2>Ocho Rios, Jamaica</h2>
        <h2>June 6 - June 10, 2018 </h2>
        <br />
    </div>
    <br />
    <br />
    <br />
    <br />
    <br />

    <!-- Countdown Timer -->
    <!-- <h1>Countdown Clock</h1> -->
    <!-- <div class="clock-container"> -->

        <div id="clockdiv">
          <div>
            <span class="days" id="day"></span>
            <div class="smalltext">Days</div>
          </div>
          <div>
            <span class="hours" id="hour"></span>
            <div class="smalltext">Hours</div>
          </div>
          <div>
            <span class="minutes" id="minute"></span>
            <div class="smalltext">Minutes</div>
          </div>
        </div>
        <br />
    <!-- End of COUNTDOWN CLOCk -->

    <!-- </div> -->

  </div>

</body>

app/views/static_pages/price.html.erb
<br />
<br />
<div class="text-center glow">
    <h2>PRICING SCHEDULE</h2>
  
    <br />
      <div class="col-10 offset-1">
        <%= image_tag("money.jpg", class: 'img-fluid, photo') %>
      </div>
      <br />
  </div>
<div class="booyah-box col-10 offset-1">
  <div class="text-center">
    TOTAL PRICE:  $966.20 (per person)
  <br />
  <br />
  <body>
    <b>(airfare NOT included ! Find your own or see contact page)</b>
    <b><li>(passports are REQUIRED)</b>
    <br />
    <br />
    <ul>  
      <li> DEPOSIT: $200.00 (per person) due by 7/15/2017
      <li> MONTHLY PAYMENT: $85.00 (per person) due on 15th of each month
      <li> FINAL PAYMENT: $86.20 due on April 15, 2018
    </ul>
    </div>
  </body>

</div>

app/views/static_pages/resort.html.erb
<br />
  <div class="glow text-center">
    <b><h1>Sandals Ochi Beach Resort</h1></b>
  </div>  
  <div class="center">

    <%= image_tag("resort.jpg", class: 'img-fluid, phototop') %>

  </div>
  <br />
  <br />

  <div class="booyah-box col-10 offset-1">
    <ul class="text-center">
        An awesome experience we will have in 2018. 
        <br />The Sandals resort is an ALL LUXURY INCLUSIVE resort. 
        <br />
        <br />
        <h2>What is included ?</h2>
        <br />
        <li> Enjoy 5 days accommodations 
        <li> (double occupancy ONLY bring your other person or contact Cynthia to be paired up)
        <li> Full access to any of the 16 restaurants featuring a variety of cuisines
        <li> All Drinks (alcohoic and non alcoholic)
        <li> All tips
        <li> Airport Transportion (to and from resort)
        <li> Non-motorized water sports
        <li> Resort Entertainment (Mechanical Bull, Glow Party)
        <li> The Caribbean's largest Rock Climbing Wall (30ft x 30 ft)
        </li>
      </ul>
  </div>
    <br />

    <div class="center col-10 offset-1">
      <%= image_tag("resort2.jpg", class: 'img-fluid, photo') %>
      <%= image_tag("resort3.jpg", class: 'img-fluid, photo') %>
      <%= image_tag("resort4.jpg", class: 'img-fluid, photo') %>
      <%= image_tag("resort5.jpg", class: 'img-fluid, photo') %>
    </div>

 